# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dominik/.local/lib/python2.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/dominik/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/MSI/Desktop/Proxy_server/Proxy_server/Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/MSI/Desktop/Proxy_server/Proxy_server/Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/dominik/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/dominik/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/MSI/Desktop/Proxy_server/Proxy_server/Server/CMakeFiles /mnt/c/Users/MSI/Desktop/Proxy_server/Proxy_server/Server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/MSI/Desktop/Proxy_server/Proxy_server/Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

HostConnector.o: HostConnector.cpp.o

.PHONY : HostConnector.o

# target to build an object file
HostConnector.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/HostConnector.cpp.o
.PHONY : HostConnector.cpp.o

HostConnector.i: HostConnector.cpp.i

.PHONY : HostConnector.i

# target to preprocess a source file
HostConnector.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/HostConnector.cpp.i
.PHONY : HostConnector.cpp.i

HostConnector.s: HostConnector.cpp.s

.PHONY : HostConnector.s

# target to generate assembly for a file
HostConnector.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/HostConnector.cpp.s
.PHONY : HostConnector.cpp.s

LogSystem/LogSystem.o: LogSystem/LogSystem.cpp.o

.PHONY : LogSystem/LogSystem.o

# target to build an object file
LogSystem/LogSystem.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/LogSystem/LogSystem.cpp.o
.PHONY : LogSystem/LogSystem.cpp.o

LogSystem/LogSystem.i: LogSystem/LogSystem.cpp.i

.PHONY : LogSystem/LogSystem.i

# target to preprocess a source file
LogSystem/LogSystem.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/LogSystem/LogSystem.cpp.i
.PHONY : LogSystem/LogSystem.cpp.i

LogSystem/LogSystem.s: LogSystem/LogSystem.cpp.s

.PHONY : LogSystem/LogSystem.s

# target to generate assembly for a file
LogSystem/LogSystem.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/LogSystem/LogSystem.cpp.s
.PHONY : LogSystem/LogSystem.cpp.s

ServerMain.o: ServerMain.cpp.o

.PHONY : ServerMain.o

# target to build an object file
ServerMain.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/ServerMain.cpp.o
.PHONY : ServerMain.cpp.o

ServerMain.i: ServerMain.cpp.i

.PHONY : ServerMain.i

# target to preprocess a source file
ServerMain.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/ServerMain.cpp.i
.PHONY : ServerMain.cpp.i

ServerMain.s: ServerMain.cpp.s

.PHONY : ServerMain.s

# target to generate assembly for a file
ServerMain.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/ServerMain.cpp.s
.PHONY : ServerMain.cpp.s

ServerOwner.o: ServerOwner.cpp.o

.PHONY : ServerOwner.o

# target to build an object file
ServerOwner.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/ServerOwner.cpp.o
.PHONY : ServerOwner.cpp.o

ServerOwner.i: ServerOwner.cpp.i

.PHONY : ServerOwner.i

# target to preprocess a source file
ServerOwner.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/ServerOwner.cpp.i
.PHONY : ServerOwner.cpp.i

ServerOwner.s: ServerOwner.cpp.s

.PHONY : ServerOwner.s

# target to generate assembly for a file
ServerOwner.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/ServerOwner.cpp.s
.PHONY : ServerOwner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Server"
	@echo "... HostConnector.o"
	@echo "... HostConnector.i"
	@echo "... HostConnector.s"
	@echo "... LogSystem/LogSystem.o"
	@echo "... LogSystem/LogSystem.i"
	@echo "... LogSystem/LogSystem.s"
	@echo "... ServerMain.o"
	@echo "... ServerMain.i"
	@echo "... ServerMain.s"
	@echo "... ServerOwner.o"
	@echo "... ServerOwner.i"
	@echo "... ServerOwner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

